---
extends: default

rules:
  line-length: false
  indentation:
    spaces: 2
    indent-sequences: false
  truthy:
    allowed-values: ['true', 'false']

ignore:
# .github: Excluded as GitHub Actions YAML files are linted by Actionlint
- '.github'
# Ignore generated and third party contracts
- 'src/lib/contracts'
- 'node_modules'
- 'pnpm-lock.yaml'
