---
services:
  frontend:
    build: .
    restart: unless-stopped
    ports:
    - '80:80'
    environment:
      BACKEND_HOST: app
      BACKEND_PORT: 8080
    networks:
    - ktor-koin-template

networks:
  ktor-koin-template:
    external: true
    name: ktor-koin-template
